[package]
name = "learn_rust"
version = "0.1.0"
edition = "2021"
authors = ["won <starship91@gmail.com>"]

[[bin]]
name = "hello"
path = "src/hello/main.rs"

[[bin]]
name = "rand"
path = "src/rand/main.rs"

[dependencies]
rand = "0.3.14"